<a href="https://colab.research.google.com/github/Tasneem-hussain/SHAPE-AI/blob/main/TASNEEM_HUSSAIN_SIDDIQUI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **IMPORTING LIBRARIES **
 ALONG WITH ALIAS

In [2]:
import pandas as pd
import numpy as np


# **EXPLORATION OF IRIS DATASET DATA **

LOADING IRIS DATASET

In [3]:
from sklearn.datasets import load_iris
iris_dataset=load_iris()

SHOWING KEY VALUES OF IRIS DATASET

In [4]:
print("keys of iris_dataset: \n{}".format(iris_dataset.keys()))


keys of iris_dataset: 
dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


DESCRIPTION OF IRIS DATASET

In [5]:
print(iris_dataset['DESCR'][:193]+"\n...")


.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, pre
...


# **SHOWING FLOWER TYPE AS TARGET NAME **

In [6]:
print("Target names: {}".format(iris_dataset['target_names']))

Target names: ['setosa' 'versicolor' 'virginica']


# **SHOWING COLUMN NAMES AS FEATURE NAME **

In [7]:
print("Feature names:\n {}".format(iris_dataset['feature_names']))

Feature names:
 ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


# **SHOWING TYPE OF DATA**

In [8]:
print("Type of data: {}".format(type(iris_dataset['data'])))

Type of data: <class 'numpy.ndarray'>


**SHOWING SHAPE OF DATA**

In [9]:
print("Shape of data: {}".format(iris_dataset['data'].shape))

Shape of data: (150, 4)


**FIRST FIVE ROWS OF DATA**

In [10]:
print("First five cooumn of data: {}".format(iris_dataset['data'][:5]))

First five cooumn of data: [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


**TYPE OF TARGET**

In [11]:
print("Type of target: {}".format(type(iris_dataset['target'])))

Type of target: <class 'numpy.ndarray'>


**SHAPE OF TARGET**

In [12]:
print("Shape of target {}".format(iris_dataset['target'].shape))

Shape of target (150,)


# **TARGET**
0 setosa

---


1 vesicolor

---


2 verginica

---




In [13]:
print("Target {}".format(iris_dataset['target']))

Target [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


# **IMPORTING TRAIN TEST SPLIT**

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
iris_dataset['data'], iris_dataset['target'], random_state=0)

# **DISPLAY SHAPE OF TRAIN TEST SPLIT**

In [23]:
print("X_train shape: {}".format(X_train.shape))
print("Y_train shape: {}".format(y_train.shape))
print("X_test shape: {}".format(X_test.shape))
print("Y_test shape: {}".format(y_test.shape))

X_train shape: (112, 4)
Y_train shape: (112,)
X_test shape: (38, 4)
Y_test shape: (38,)


# **K NEAREST VALUE**

---



**IMPORTING K NEIGHBOUR CLASSIFIER**



In [28]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

**DESCRIPTION OF K NEIGHOR CLASSIFIER**

In [29]:
knn.fit(X_train, y_train)


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

***ADDING ANOTHER ROW ***

In [30]:
X_new = np.array([[5,2.9,1,0.2]])
print("X_new.shape: {}".format(X_new.shape))


X_new.shape: (1, 4)


***PREDICION OF TARGET AND TARGET NAME ***

In [31]:
prediction = knn.predict(X_new)
print("Prediction: {}".format(prediction))
print("Predicted target name: {}".format(iris_dataset['target_names'][prediction]))

Prediction: [0]
Predicted target name: ['setosa']


In [32]:
y_pred = knn.predict(X_test)
print("Test set prediction:\n{}".format(y_pred))

Test set prediction:
[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


# **VERIFICATION AD CONFIRMATION OF PREDICTION**

---



In [33]:
print("Test set score: {}".format(np.mean(y_pred==y_test)))

Test set score: 0.9736842105263158
